# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: frontend
    steps:
      - uses: actions/checkout@v2
      - name: jest
        uses: actions/checkout@v1
        with:
          node-version: 14.x
      - name: install
      - run: |
          cd ./webapp
          npm install
      - name: test
      - run: |
          cd ./webapp
          npm test

    
